[package]
name = "bsky-skylog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aerostream = "*"
chrono = "0.4.34"
tokio = "1.36.0"
